apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: {{ include "greatdb.cmpdName" . }}
  labels:
    {{- include "greatdb.labels" . | nindent 4 }}
  annotations:
    {{- include "greatdb.annotations" . | nindent 4 }}
spec:
  provider: Community
  description: {{ .Chart.Description }}
  serviceKind: {{ .Chart.Name }}
  serviceVersion: {{ .Values.defaultServiceVersion.greatdb }}
  configs:
    - name: greatdb-config
      template: greatdb-config
      namespace: {{ .Release.Namespace }}
      volumeName: greatdb-config
      defaultMode: 0755
      keys:
        - my.cnf
      restartOnFileChange: true
  scripts:
    - name: greatdb-scripts
      template: greatdb-scripts
      namespace: {{ .Release.Namespace }}
      volumeName: greatdb-scripts
      defaultMode: 0555
  services:
    - name: mysql
      serviceName: mysql
      spec:
        ports:
          - name: mysql
            port: {{ .Values.service.port }}
            targetPort: mysql
  roles:
    - name: primary
      updatePriority: 2
      participatesInQuorum: false
      isExclusive: true
    - name: secondary
      updatePriority: 1
      participatesInQuorum: false
  lifecycleActions:
    accountProvision:
      exec:
        container: greatdb
        command:
          - bash
          - -c
          - |
            set -ex
            ALL_DB='*.*'
            eval statement=\"${KB_ACCOUNT_STATEMENT}\"
            greatdb -u${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} -P3306 -h127.0.0.1 -e "${statement}"
        targetPodSelector: Role
        matchingKey: primary
    roleProbe:
      periodSeconds: {{ .Values.roleProbe.periodSeconds }}
      timeoutSeconds: {{ .Values.roleProbe.timeoutSeconds }}
      exec:
        container: greatdb
        command:
          - /bin/bash
          - -c
          - /scripts/greatdb/role-probe.sh
    memberJoin:
      exec:
        container: greatdb
        command:
          - /bin/bash
          - -c
          - /scripts/greatdb/setup-replica.sh
    memberLeave:
      exec:
        container: greatdb
        command:
          - /bin/bash
          - -c
          - /scripts/greatdb/leave-member.sh
    switchover:
      exec:
        container: greatdb
        command:
          - /bin/bash
          - -c
          - /scripts/greatdb/switchover.sh
  systemAccounts:
    - name: root
      initAccount: true
      passwordGenerationPolicy:
        length: 16
        numDigits: 8
        numSymbols: 0
        letterCase: MixedCases
    - name: monitor
      initAccount: true
      passwordGenerationPolicy:
        length: 16
        numDigits: 8
        numSymbols: 0
        letterCase: MixedCases
    - name: default
      initAccount: true
      passwordGenerationPolicy:
        length: 16
        numDigits: 8
        numSymbols: 0
        letterCase: MixedCases
    - name: kbadmin
      statement:
        create: "select 1;"
      passwordGenerationPolicy: &defaultPasswordGenerationPolicy
        length: 16
        numDigits: 8
        numSymbols: 0
        letterCase: MixedCases
    - name: kbdataprotection
      statement:
        create: "CREATE USER ${KB_ACCOUNT_NAME} IDENTIFIED BY '${KB_ACCOUNT_PASSWORD}';GRANT RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT ON ${ALL_DB} TO ${KB_ACCOUNT_NAME}; GRANT LOCK TABLES,RELOAD,PROCESS,REPLICATION CLIENT, SUPER,SELECT,EVENT,TRIGGER,SHOW VIEW ON ${ALL_DB} TO ${KB_ACCOUNT_NAME};"
      passwordGenerationPolicy: *defaultPasswordGenerationPolicy
    - name: kbprobe
      statement:
        create: "CREATE USER ${KB_ACCOUNT_NAME} IDENTIFIED BY '${KB_ACCOUNT_PASSWORD}'; GRANT REPLICATION CLIENT, PROCESS ON ${ALL_DB} TO ${KB_ACCOUNT_NAME}; GRANT SELECT ON performance_schema.* TO ${KB_ACCOUNT_NAME};"
      passwordGenerationPolicy: *defaultPasswordGenerationPolicy
    - name: kbmonitoring
      statement:
        create: "CREATE USER ${KB_ACCOUNT_NAME} IDENTIFIED BY '${KB_ACCOUNT_PASSWORD}'; GRANT REPLICATION CLIENT, PROCESS ON ${ALL_DB} TO ${KB_ACCOUNT_NAME}; GRANT SELECT ON performance_schema.* TO ${KB_ACCOUNT_NAME};"
      passwordGenerationPolicy: *defaultPasswordGenerationPolicy
    - name: replication
      statement:
        create: "CREATE USER ${KB_ACCOUNT_NAME} IDENTIFIED BY '${KB_ACCOUNT_PASSWORD}'; GRANT REPLICATION SLAVE ON *.* TO ${KB_ACCOUNT_NAME};"
      passwordGenerationPolicy: *defaultPasswordGenerationPolicy
  runtime:
    containers:
      - name: greatdb
        image: {{ include "greatdb.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /etc/mysql/conf.d
            name: greatdb-config
            readOnly: true
          - mountPath: /etc/greatdb/my.cnf
            name: greatdb-config
            subPath: my.cnf
            readOnly: true
          - mountPath: /scripts/greatdb
            name: greatdb-scripts
            readOnly: true
          - mountPath: /var/lib/mysql
            name: data
        ports:
          - containerPort: 3306
            name: mysql
        env:
          - name: MYSQL_ROOT_HOST
            value: {{ .Values.auth.rootHost | default "%" | quote }}
          - name: MYSQL_ROOT_PASSWORD
            value: $(MYSQL_ROOT_PASSWORD)
          - name: MYSQL_DATABASE
            value: {{ .Values.auth.database | quote }}
          - name: MYSQL_USER
            value: "greatdb"
          - name: MYSQL_PASSWORD
            value: $(MYSQL_PASSWORD)
        command:
          - docker-entrypoint.sh
          - greatdbd
          - --defaults-file=/etc/greatdb/my.cnf
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "mysqladmin -u$(MYSQL_ROOT_USER) -p$(MYSQL_ROOT_PASSWORD) shutdown"]
      - name: exporter
        image: {{ include "exporter.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.prom.pullPolicy }}
        ports:
          - name: metrics
            containerPort: 9104
            protocol: TCP
        env:
          - name: "DATA_SOURCE_NAME"
            value: "$(MYSQL_ROOT_USER):$(MYSQL_ROOT_PASSWORD)@(localhost:3306)/"
  vars:
    - name: MYSQL_ROOT_USER
      value: root
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        credentialVarRef:
          name: root
          optional: false
          password: Required
    - name: MYSQL_MONITOR_USER
      value: monitor
    - name: MYSQL_MONITOR_PASSWORD
      valueFrom:
        credentialVarRef:
          name: monitor
          optional: false
          password: Required
    - name: MYSQL_USER
      value: greatdb
    - name: MYSQL_PASSWORD
      valueFrom:
        credentialVarRef:
          name: default
          optional: false
          password: Required
    - name: MYSQL_DATABASE
      value: {{ .Values.auth.database | quote }}
    - name: PRIMARY_POD_FQDN
      valueFrom:
        componentVarRef:
          optional: true
          podFQDNsForRole:
            role: primary
            option: Optional
    - name: POD_FQDNS
      valueFrom:
        componentVarRef:
          optional: false
          podFQDNs: Required
    - name: MYSQL_REPL_USER
      value: replication
    - name: MYSQL_REPL_PASSWORD
      valueFrom:
        credentialVarRef:
          name: replication
          optional: false
          password: Required
